### ISSUE TITLE
Add `tmp` dir to the .npmignore.

### ISSUE THREAD

**Issue by stefanpenner** [williamsbdev/ember-cli-injection#1]
https://github.com/ember-cli/ember-cli/issues/4199

**Comment by stefanpenner** [comment]
like: https://github.com/ember-cli/ember-cli/commit/6ac18227ea571988fa9d9950e9a1051fdd990c7c

**Comment by williamsbdev** [comment]
Thank you for bringing this to my attention but this addon already has that. :)

https://github.com/williamsbdev/ember-cli-injection/blob/master/.npmignore#L3
