### ISSUE TITLE
Ambiguous injection

### ISSUE THREAD

**Issue by estshy** [williamsbdev/ember-cli-injection#6]
I am using pods structure and I have quite a lot of services and custom repositories. Sometimes I am facing naming issues, see an example

```
Ember.Route.extend({
   domains: Ember.inject.service(),
   domains: injectRepo(),
});
```

I can not use both of them on the same time without using aliases which is kind of awkward so I came up with custom injection method

```
const injection = function(key) {
  return function(name) {
    return Ember.computed(function(propertyName) {
      const objectName = name || propertyName.replace(key.capitalize(), '');
      return Ember.getOwner(this).lookup(key + ':' + objectName.decamelize().replace('_', '/'));
    });
  };
};
```

which allows me to do

```
Ember.Route.extend({
   domains: Ember.inject.service(),
   domainsRepository: injectRepo(),
});
```

in addition to that I've created an convenient alias

```
Ember.inject.repository = injection('repository')
```

I would be nice to see solution to this problem directly in this repository so I would not relay on custom code ;). @williamsbdev  What's your opinion?

**Comment by williamsbdev** [comment]
@estshy - As for the last example with the alias `Ember.inject.repository`, I am on board for figuring  out a solution to make this work for you. In a conversation I had with @rwjblue, he discovered me from appending anything to an official Ember API. I tend to agree and would like to not do that.

As for your other example, would you be able to provide me a test case that shows you can make this work with all the existing scenarios? I would be happy to help you get this functionality.

**Comment by williamsbdev** [comment]
@estshy - I am going to close this issue. If you have a solution to this, please submit a PR. Thanks!
